#!/bin/bash
# install-matrix.sh — Install Continuwuity Matrix homeserver + Caddy on Ubuntu LXC
#
# Usage: Run inside a fresh Ubuntu LXC container via Proxmox console:
#   bash install-matrix.sh
#
# What it does:
#   1. Installs system packages (curl, wget, ca-certificates, gpg)
#   2. Installs Continuwuity from official apt repo
#   3. Writes conduwuit.toml config (federation disabled, local-only)
#   4. Creates init.d service (SysV — no systemd in LXC)
#   5. Installs Caddy reverse proxy for TLS
#   6. Configures firewall (ufw — SSH + HTTPS only)
#   7. Starts services and verifies
#
# After running:
#   1. Create user accounts (see output instructions)
#   2. Connect with Element Desktop
#
# Sources:
#   - https://continuwuity.org/deploying/debian
#   - https://caddyserver.com/docs/install#debian-ubuntu-raspbian

set -euo pipefail

# --- Configuration ---
SERVER_NAME="${MATRIX_SERVER_NAME:-matrix.example.com}"
LISTEN_PORT="6167"
REG_TOKEN="${MATRIX_REG_TOKEN:-$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)}"
DATA_DIR="/var/lib/conduwuit"

# --- Colors for output ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
step()  { echo -e "\n${GREEN}━━━ Step $1: $2 ━━━${NC}"; }

# --- Preflight checks ---
if [ "$(id -u)" -ne 0 ]; then
    error "Must run as root"
    exit 1
fi

if ! grep -qi 'ubuntu' /etc/os-release 2>/dev/null; then
    warn "Expected Ubuntu — detected: $(. /etc/os-release && echo "$PRETTY_NAME")"
    warn "Continuing anyway..."
fi

# Auto-detect container IP
CONTAINER_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
if [ -z "$CONTAINER_IP" ]; then
    CONTAINER_IP=$(ip -4 addr show scope global | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)
fi
if [ -z "$CONTAINER_IP" ]; then
    warn "Could not detect container IP — using 0.0.0.0"
    CONTAINER_IP="0.0.0.0"
fi
info "Detected container IP: ${CONTAINER_IP}"

# --- Step 1: System packages ---
step 1 "Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl wget ca-certificates gnupg lsb-release ufw iproute2 procps >/dev/null 2>&1
info "Packages installed"

# --- Step 2: Install Continuwuity ---
step 2 "Installing Continuwuity Matrix homeserver"

if command -v conduwuit &>/dev/null; then
    info "Continuwuity (conduwuit) already installed: $(conduwuit --version 2>/dev/null || echo 'version unknown')"
else
    # Add Continuwuity apt repository (Forgejo package registry)
    install -d -m 0755 /etc/apt/keyrings

    # Download and add signing key
    if [ ! -f /etc/apt/keyrings/forgejo-continuwuation.asc ]; then
        curl -fsSL https://forgejo.ellis.link/api/packages/continuwuation/debian/repository.key \
            -o /etc/apt/keyrings/forgejo-continuwuation.asc
        info "Added Continuwuity signing key"
    fi

    # Add repository
    COMPONENT="stable"
    CODENAME=$(lsb_release -sc 2>/dev/null || echo "noble")
    if [ ! -f /etc/apt/sources.list.d/continuwuation.list ]; then
        echo "deb [signed-by=/etc/apt/keyrings/forgejo-continuwuation.asc] https://forgejo.ellis.link/api/packages/continuwuation/debian ${CODENAME} ${COMPONENT}" \
            > /etc/apt/sources.list.d/continuwuation.list
        info "Added Continuwuity apt repository"
    fi

    apt-get update -qq
    apt-get install -y -qq continuwuity >/dev/null 2>&1 || apt-get install -y -qq conduwuit >/dev/null 2>&1
    info "Continuwuity installed"
fi

# --- Step 3: Configure Continuwuity ---
step 3 "Configuring Continuwuity"

# Create data directory
install -d -m 750 -o conduwuit -g conduwuit "$DATA_DIR" 2>/dev/null || {
    # If conduwuit user doesn't exist yet, create it
    if ! id conduwuit &>/dev/null; then
        adduser --system --group --no-create-home --home "$DATA_DIR" conduwuit
        info "Created conduwuit system user"
    fi
    install -d -m 750 -o conduwuit -g conduwuit "$DATA_DIR"
}

# Write config (only if it doesn't exist — preserve manual edits)
CONF_DIR="/etc/conduwuit"
install -d -m 755 "$CONF_DIR"

if [ -f "$CONF_DIR/conduwuit.toml" ]; then
    warn "conduwuit.toml already exists — skipping (delete it to regenerate)"
else
    cat > "$CONF_DIR/conduwuit.toml" << EOF
# Continuwuity Matrix homeserver configuration
# Generated by install-matrix.sh

[global]
# Server identity
server_name = "${SERVER_NAME}"

# Network — bind to localhost only (Caddy handles external traffic)
address = "127.0.0.1"
port = ${LISTEN_PORT}

# Database
database_path = "${DATA_DIR}"

# Security — no federation, no public registration
allow_federation = false
allow_registration = true
registration_token = "${REG_TOKEN}"

# Performance tuning for single-user
max_request_size = 20_000_000

# Logging
log = "warn,state_res=warn"
EOF
    chown root:conduwuit "$CONF_DIR/conduwuit.toml"
    chmod 640 "$CONF_DIR/conduwuit.toml"
    info "Wrote $CONF_DIR/conduwuit.toml"
fi

# --- Step 4: Continuwuity init.d service ---
step 4 "Creating Continuwuity init.d service"

cat > /etc/init.d/conduwuit << 'INITEOF'
#!/bin/sh
### BEGIN INIT INFO
# Provides:          conduwuit
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Continuwuity Matrix homeserver
# Description:       Continuwuity — lightweight Rust Matrix homeserver
### END INIT INFO

DAEMON=/usr/bin/conduwuit
NAME=conduwuit
PIDFILE=/var/run/conduwuit.pid
USER=conduwuit
GROUP=conduwuit
WORKDIR=/var/lib/conduwuit
CONF=/etc/conduwuit/conduwuit.toml
LOGFILE=/var/log/conduwuit.log

export CONDUWUIT_CONFIG="$CONF"

do_start() {
    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
        echo "$NAME is already running"
        return 0
    fi
    echo "Starting $NAME..."
    start-stop-daemon --start --quiet --background \
        --make-pidfile --pidfile "$PIDFILE" \
        --chuid "$USER:$GROUP" --chdir "$WORKDIR" \
        --startas /bin/sh -- -c "exec $DAEMON >> $LOGFILE 2>&1"
}

do_stop() {
    if [ ! -f "$PIDFILE" ] || ! kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
        echo "$NAME is not running"
        return 0
    fi
    echo "Stopping $NAME..."
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE" --retry=TERM/10/KILL/5
    rm -f "$PIDFILE"
}

do_status() {
    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
        echo "$NAME is running (PID $(cat "$PIDFILE"))"
        return 0
    else
        echo "$NAME is not running"
        return 1
    fi
}

case "$1" in
    start)   do_start ;;
    stop)    do_stop ;;
    restart) do_stop; sleep 1; do_start ;;
    status)  do_status ;;
    *)       echo "Usage: $0 {start|stop|restart|status}"; exit 1 ;;
esac
INITEOF

chmod 755 /etc/init.d/conduwuit
update-rc.d conduwuit defaults
touch /var/log/conduwuit.log
chown conduwuit:conduwuit /var/log/conduwuit.log
info "Continuwuity init.d service created and enabled"

# --- Step 5: Install Caddy ---
step 5 "Installing Caddy reverse proxy"

if command -v caddy &>/dev/null; then
    info "Caddy already installed: $(caddy version 2>/dev/null || echo 'version unknown')"
else
    # Add Caddy apt repository
    curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/gpg.key | gpg --dearmor -o /etc/apt/keyrings/caddy-stable.gpg 2>/dev/null
    echo "deb [signed-by=/etc/apt/keyrings/caddy-stable.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main" \
        > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -qq
    apt-get install -y -qq caddy >/dev/null 2>&1
    info "Caddy installed"
fi

# Write Caddyfile (only if it doesn't exist)
if [ -f /etc/caddy/Caddyfile ] && grep -q "conduwuit\|matrix\|${LISTEN_PORT}" /etc/caddy/Caddyfile; then
    warn "Caddyfile already configured for Matrix — skipping"
else
    cat > /etc/caddy/Caddyfile << EOF
# Matrix homeserver reverse proxy
# Generated by install-matrix.sh

${SERVER_NAME} {
    # Matrix Client-Server API
    reverse_proxy /_matrix/* 127.0.0.1:${LISTEN_PORT}

    # Well-known delegation (for client auto-discovery)
    handle /.well-known/matrix/client {
        header Content-Type application/json
        respond \`{"m.homeserver": {"base_url": "https://${SERVER_NAME}"}}\` 200
    }

    handle /.well-known/matrix/server {
        header Content-Type application/json
        respond \`{"m.server": "${SERVER_NAME}:443"}\` 200
    }

    # Self-signed TLS for local network
    tls internal
}
EOF
    info "Wrote /etc/caddy/Caddyfile"
fi

# Caddy service (init.d)
if [ ! -f /etc/init.d/caddy ]; then
    cat > /etc/init.d/caddy << 'CADDYEOF'
#!/bin/sh
### BEGIN INIT INFO
# Provides:          caddy
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Caddy web server
# Description:       Caddy — fast, cross-platform HTTP/2 web server with automatic HTTPS
### END INIT INFO

DAEMON=/usr/bin/caddy
NAME=caddy
PIDFILE=/var/run/caddy.pid
LOGFILE=/var/log/caddy.log
CADDYFILE=/etc/caddy/Caddyfile

do_start() {
    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
        echo "$NAME is already running"
        return 0
    fi
    echo "Starting $NAME..."
    start-stop-daemon --start --quiet --background \
        --make-pidfile --pidfile "$PIDFILE" \
        --exec "$DAEMON" -- run --config "$CADDYFILE" >> "$LOGFILE" 2>&1
}

do_stop() {
    if [ ! -f "$PIDFILE" ] || ! kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
        echo "$NAME is not running"
        return 0
    fi
    echo "Stopping $NAME..."
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE" --retry=TERM/10/KILL/5
    rm -f "$PIDFILE"
}

do_status() {
    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
        echo "$NAME is running (PID $(cat "$PIDFILE"))"
        return 0
    else
        echo "$NAME is not running"
        return 1
    fi
}

do_reload() {
    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
        echo "Reloading $NAME..."
        $DAEMON reload --config "$CADDYFILE"
    else
        echo "$NAME is not running"
        return 1
    fi
}

case "$1" in
    start)   do_start ;;
    stop)    do_stop ;;
    restart) do_stop; sleep 1; do_start ;;
    reload)  do_reload ;;
    status)  do_status ;;
    *)       echo "Usage: $0 {start|stop|restart|reload|status}"; exit 1 ;;
esac
CADDYEOF
    chmod 755 /etc/init.d/caddy
    info "Caddy init.d service created"
fi

update-rc.d caddy defaults
touch /var/log/caddy.log
info "Caddy service enabled"

# --- Step 6: Firewall ---
step 6 "Configuring firewall"

if command -v ufw &>/dev/null; then
    ufw --force reset >/dev/null 2>&1
    ufw default deny incoming >/dev/null
    ufw default allow outgoing >/dev/null
    ufw allow 22/tcp >/dev/null    # SSH
    ufw allow 443/tcp >/dev/null   # HTTPS (Matrix via Caddy)
    ufw --force enable >/dev/null
    info "Firewall configured: SSH (22) + HTTPS (443) only"
else
    warn "ufw not available — install manually or configure iptables"
fi

# --- Step 7: Start services and verify ---
step 7 "Starting services"

service conduwuit start
sleep 2

# Check conduwuit
if service conduwuit status >/dev/null 2>&1; then
    info "Continuwuity is running"
else
    warn "Continuwuity may still be starting — check: cat /var/log/conduwuit.log"
fi

# Wait for HTTP to come up (up to 15s)
for i in $(seq 1 15); do
    HTTP_CODE=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:${LISTEN_PORT}/_matrix/client/versions 2>/dev/null || echo "000")
    if [ "$HTTP_CODE" != "000" ]; then
        break
    fi
    sleep 1
done

if [ "$HTTP_CODE" = "200" ]; then
    info "Continuwuity HTTP responding (status ${HTTP_CODE})"
else
    warn "Continuwuity HTTP status: ${HTTP_CODE} — may still be starting. Check: cat /var/log/conduwuit.log"
fi

# Start Caddy
service caddy start
sleep 2

if service caddy status >/dev/null 2>&1; then
    info "Caddy is running"
else
    warn "Caddy may still be starting — check: cat /var/log/caddy.log"
fi

# --- Summary ---
echo ""
echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Continuwuity Matrix Server installed successfully${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
echo ""
echo "  Server name:  ${SERVER_NAME}"
echo "  Internal:     http://127.0.0.1:${LISTEN_PORT}"
echo "  External:     https://${SERVER_NAME} (via Caddy)"
echo "  Container IP: ${CONTAINER_IP}"
echo ""
echo "  Config:       /etc/conduwuit/conduwuit.toml"
echo "  Data:         ${DATA_DIR}/"
echo "  Logs:         /var/log/conduwuit.log"
echo "  Caddy:        /etc/caddy/Caddyfile"
echo "  Firewall:     SSH (22) + HTTPS (443) only"
echo ""
echo "  Services:     service conduwuit status"
echo "                service caddy status"
echo ""
echo -e "${YELLOW}  NEXT STEPS:${NC}"
echo ""
echo "  1. Add DNS: ${SERVER_NAME} → ${CONTAINER_IP}"
echo "     (local DNS or /etc/hosts on your workstation)"
echo ""
echo "  2. Create your user account:"
echo "     curl -X POST http://localhost:${LISTEN_PORT}/_matrix/client/v3/register \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"username\":\"me\",\"password\":\"CHANGEME\",\"auth\":{\"type\":\"m.login.registration_token\",\"token\":\"${REG_TOKEN}\"}}'"
echo ""
echo "  3. Create Robot bot account:"
echo "     curl -X POST http://localhost:${LISTEN_PORT}/_matrix/client/v3/register \\"
echo "       -H 'Content-Type: application/json' \\"
echo "       -d '{\"username\":\"robot\",\"password\":\"CHANGEME\",\"auth\":{\"type\":\"m.login.registration_token\",\"token\":\"${REG_TOKEN}\"}}'"
echo ""
echo "  4. IMPORTANT: After creating accounts, disable registration:"
echo "     Edit /etc/conduwuit/conduwuit.toml → set allow_registration = false"
echo "     service conduwuit restart"
echo ""
echo "  5. Connect with Element Desktop:"
echo "     Homeserver: https://${SERVER_NAME}"
echo ""
echo -e "  Registration token: ${YELLOW}${REG_TOKEN}${NC}"
echo "  (Save this! Needed for account creation in steps 2-3)"
echo ""
